### ISSUE TITLE
First error reason: Could not find trained model [.elser_model_1] when trying workplace-search

### ISSUE THREAD

**Issue by alexey2baranov** [elastic/elasticsearch-labs#103]
Can't execute index-data.py

step to reproduce
1. clone repo
2. cd workplace-search
3. install requirements.txt
4. Cange ES Client connection to http://localhost:9200
5. run  index-data.py

> Loaded 1 documents
> Split 1 documents into 104 chunks
> Creating Elasticsearch sparse vector store in Elastic Cloud: None
> Error adding texts: 104 document(s) failed to index.
> First error reason: Could not find trained model [.elser_model_1]
> Traceback (most recent call last):
>   File "/home/aleksei/code/elasticsearch-labs/example-apps/workplace-search/./data/index-data.py", line 52, in <module>
>     ElasticsearchStore.from_documents(
>   File "/home/aleksei/.local/lib/python3.10/site-packages/langchain/vectorstores/elasticsearch.py", line 1125, in from_documents
>     elasticsearchStore.add_documents(documents, bulk_kwargs=bulk_kwargs)
>   File "/home/aleksei/.local/lib/python3.10/site-packages/langchain/schema/vectorstore.py", line 122, in add_documents
>     return self.add_texts(texts, metadatas, **kwargs)
>   File "/home/aleksei/.local/lib/python3.10/site-packages/langchain/vectorstores/elasticsearch.py", line 971, in add_texts
>     raise e
>   File "/home/aleksei/.local/lib/python3.10/site-packages/langchain/vectorstores/elasticsearch.py", line 954, in add_texts
>     success, failed = bulk(
>   File "/home/aleksei/.local/lib/python3.10/site-packages/elasticsearch/helpers/actions.py", line 521, in bulk
>     for ok, item in streaming_bulk(
>   File "/home/aleksei/.local/lib/python3.10/site-packages/elasticsearch/helpers/actions.py", line 436, in streaming_bulk
>     for data, (ok, info) in zip(
>   File "/home/aleksei/.local/lib/python3.10/site-packages/elasticsearch/helpers/actions.py", line 355, in _process_bulk_chunk
>     yield from gen
>   File "/home/aleksei/.local/lib/python3.10/site-packages/elasticsearch/helpers/actions.py", line 274, in _process_bulk_chunk_success
>     raise BulkIndexError(f"{len(errors)} document(s) failed to index.", errors)
> elasticsearch.helpers.BulkIndexError: 104 document(s) failed to index.
>

**Comment by joemcelroy** [comment]
Hi there,

You need to deploy the ELSER model to use workplace-search in the ML node. You can also change the strategy in the code to not use ELSER and use approx if you want to do embeddings in langchain.
