### ISSUE TITLE
ModuleNotFoundError: No module named 'dotenv'  when trying workplace-search

### ISSUE THREAD

**Issue by alexey2baranov** [elastic/elasticsearch-labs#104]
Can't execute index-data.py

step to reproduce

1. clone repo
2. cd workplace-search
3. create virtual env
4. install requirements.txt
5. run python3 data/index-data.py

(.venv) aleksei@EPRSBELL001B:~/code/elasticsearch-labs/example-apps/workplace-search$ python3 data/index-data.py
Traceback (most recent call last):
  File "/home/aleksei/code/elasticsearch-labs/example-apps/workplace-search/data/index-data.py", line 3, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'

**Comment by joemcelroy** [comment]
Thanks! Now resolved in latest updates :)
