### ISSUE TITLE
What is the reason for "elasticsearch.BadRequestError: BadRequestError(400, 'x_content_parse_exception', '[1:137] unknown field [xlm_roberta]')"?

### ISSUE THREAD

**Issue by thomassuedbroecker** [elastic/elasticsearch-labs#112]
1. What do I want? 

   I want to install an additional NLP model to Elasticsearch. The model is called `multilingual-e5-base`. 

 2. What did I do? 

    Therefore, I followed the steps in [Elasticsearch
    documentation](https://www.elastic.co/guide/en/machine-learning/current/ml-nlp-import-model.html).
    
 3. What I expected?

    The ```multilingual-e5-base``` is successfully installed.
 
4. What I tried?

Here is the relevant section in my Python Notebook for the installation:

```sh
!source ../.env && \
eland_import_hub_model \
    --url ${REMOTE_HOST} \
    --es-username ${USER} \
    --es-password ${API_KEY} \
    --hub-model-id intfloat/multilingual-e5-base \
    --es-model-id multilingual-e5-base \
    --task-type text_embedding \
    --start
```

**Error message:**

```sh
raise HTTP_EXCEPTIONS.get(meta.status, ApiError)(
elasticsearch.BadRequestError: BadRequestError(400, 'x_content_parse_exception', '[1:137] unknown field [xlm_roberta]')
```
_Note:_ I posted the same question on stackoverflow [link](https://stackoverflow.com/questions/77472800/what-is-the-reason-for-elasticsearch-badrequesterror-badrequesterror400-x-c)

**Comment by joemcelroy** [comment]
Hi there!

Looks like you got an answer on SO, where you need at least 8.9 or above to use this model.

Joe
