### ISSUE TITLE
Wrong fields used in the filter and aggregation

### ISSUE THREAD

**Issue by liu-xiao-guo** [elastic/elasticsearch-labs#126]
For the notebook at https://github.com/elastic/elasticsearch-labs/blob/main/supporting-blog-content/vector-search-implementation-guide-api/vector_search_implementation_guide_api.ipynb, "my_metadata" is a text field, and it should not be used in the term filter, and it is the same for the aggregation. The correct one should be "my_metadata.keyword".

![image](https://github.com/elastic/elasticsearch-labs/assets/8455957/9dac7b13-65f9-4595-b80c-f06189e6e24d)
![image](https://github.com/elastic/elasticsearch-labs/assets/8455957/843b1c43-c9ac-4f6d-a08c-1144f0ddd99e)

**Comment by miguelgrinberg** [comment]
@jeffvestal Will you be looking at this? The corresponding blog article needs to be fixed as well, it appears.

**Comment by serenachou** [comment]
@jeffvestal  just a ping on this one
