### ISSUE TITLE
GOOGLE_APPLICATION_CREDENTIALS json-service-account-file cannot be found

### ISSUE THREAD

**Issue by bvader** [elastic/elasticsearch-labs#135]
The application cannot find the `json-service-account-file` per the given instructions and thus fails on a permission error. 
The credential file needs to be copied into one of the directories that is copied into the container by the `Dockerfile` so it can be found by the app. 
My suggestion is to copy the file into the data directory and then set the path accordingly

My suggestion is the following for the Vertex AI Section

### Vertex AI

To use Vertex AI you need to set the following environment variables. More info [here](https://python.langchain.com/docs/integrations/llms/google_vertex_ai_palm).

copy your `json-service-account-file` into the `data` directory and set the path accordingly

```sh
export LLM_TYPE=vertex
export VERTEX_PROJECT_ID=<gcp-project-id>
export VERTEX_REGION=<gcp-region> # Default is us-central1
export GOOGLE_APPLICATION_CREDENTIALS=/data/<json-service-account-file>
```

**Comment by miguelgrinberg** [comment]
I think I prefer not to use the `data` directory for storing sensitive files. Would it be enough to add a note in the Docker section indicating that if Vertex AI is used the developer needs to add a `COPY` for the credentials file?
