### ISSUE TITLE
Blog Proposal - Ingest data from Snowflake to Elasticsearch

### ISSUE THREAD

**Issue by ashishtiwari1993** [elastic/elasticsearch-labs#137]
## Ingest data from Snowflake to Elasticsearch

[Blog Content](https://docs.google.com/document/d/1d8Ek5S3R-e4NoiKYYs_IJabN2Qbw2cB8o0rMqnHn8xg/edit?usp=sharing)

**Comment by joemcelroy** [comment]
sent ashish instructions on how to write up a blog :)
