### ISSUE TITLE
Positional arguments do not work for TransformerModel and wrong pipeline name used in the code for plagiarism demo

### ISSUE THREAD

**Issue by liu-xiao-guo** [elastic/elasticsearch-labs#144]
For the example app at https://github.com/elastic/elasticsearch-labs/blob/main/supporting-blog-content/plagiarism-detection-with-elasticsearch/plagiarism_detection_es.ipynb. I find there are following issues:

1)  According to code at https://github.com/elastic/eland/blob/main/eland/ml/pytorch/transformers.py, 
`class TransformerModel:
    def __init__(
        self,
        *,
        model_id: str,
        task_type: str,
        es_version: Optional[Tuple[int, int, int]] = None,
        quantize: bool = False,
        access_token: Optional[str] = None,
    ):
`
It needs to have keyword arguments for the constructor. I am not sure the demo uses which eland version. I use the latest version:
`$ pip3 list | grep eland
eland                     8.11.1`

The call in the code:
`tm = TransformerModel(hf_model_id, "text_embedding")`

does not work. The working one is:

`tm = TransformerModel(model_id=hf_model_id, task_type="text_embedding")`

This applies to the code as well:
`tm = TransformerModel(hf_model_id, "text_classification")`

2) pipeline name is spelled wrongly in the code:

`client.reindex(wait_for_completion=True,
               source={
                  "index": "plagiarism-docs"
    },
               dest= {
                  "index": "plagiarism-checker",
                  "pipeline": "plagiarism-pipeline"
    }
)`

In the code, "plagiarism-pipeline" pipeline is never created. It should be "plagiarism-checker-pipeline".

3) The synchronous call for the reindex seems not working at all.

`client.reindex(wait_for_completion=True,
               source={
                  "index": "plagiarism-docs"
    },
               dest= {
                  "index": "plagiarism-checker",
                  "pipeline": "plagiarism-pipeline"
    }
)`

It always returns "Connection time out" error. I have to change it to False to make it work.

**Comment by miguelgrinberg** [comment]
Issue 2 has already been address, as we had another bug report for it (#148).

@priscillaparodi Could you look at items 1 and 3 above?

**Comment by priscillaparodi** [comment]
3 is solved after the pipeline name update (item 2). I can’t reproduce the item 1 error, it is working, the model id was defined before.

**Comment by miguelgrinberg** [comment]
@priscillaparodi The eland code referenced above agrees with what @liu-xiao-guo is saying. The constructor of the latest version of `TransformerModel` only takes keyword arguments, but you are passing the model id as a positional argument. Wouldn't it make sense to change the notebook to use keyword arguments here? The current version of the code seems broken.

**Comment by priscillaparodi** [comment]
I will check based on the latest version and update accordingly.

**Comment by priscillaparodi** [comment]
https://github.com/elastic/elasticsearch-labs/pull/156
