### ISSUE TITLE
Unnecessary if statement in search tutorial

### ISSUE THREAD

**Issue by t10kiyotaka** [elastic/elasticsearch-labs#176]
An unnecessary if statement exists in the following page.

https://www.elastic.co/search-labs/tutorials/search-tutorial/full-text-search/filters

![](https://github.com/elastic/elasticsearch-labs/assets/26037159/245df9d3-f01d-46f0-9c07-680fb99c14c1)

**Comment by miguelgrinberg** [comment]
Thanks for the report. You are correct, that if statement was a left over from a previous version of this tutorial that should have been removed in the last update. I have updated that code example now. Thanks!
