### ISSUE TITLE
mappings link  does not exist for the internal-knowledge-search example

### ISSUE THREAD

**Issue by liu-xiao-guo** [elastic/elasticsearch-labs#181]
As described in the readme file, the following link does not exist at all: https://github.com/elastic/elasticsearch-labs/blob/main/example-apps/internal-knowledge-search/src/config/documentsToSearchResultMappings.json

<img width="1184" alt="image" src="https://github.com/elastic/elasticsearch-labs/assets/8455957/a6a1694d-089f-4a79-bb96-bd2f132e6c3b">

In addition, I read the blog at https://www.elastic.co/search-labs/blog/articles/dls-internal-knowledge-search. I I am not wrong, the DIS should be DLS, right?

<img width="1060" alt="image" src="https://github.com/elastic/elasticsearch-labs/assets/8455957/371da29d-917b-4246-9b59-9312ab06310d">

**Comment by seanstory** [comment]
> the following link does not exist at all

Thanks for flagging! Fixed in https://github.com/elastic/elasticsearch-labs/pull/184

> I am not wrong, the DIS should be DLS, right?

Woops! Yep. Looks like my finger came off of "shift" in the middle of typing that. :) Will get that fixed.
