### ISSUE TITLE
Customizing the UI?

### ISSUE THREAD

**Issue by rupamGH** [elastic/elasticsearch-labs#187]
Is there a way to customize the UI?

**Comment by miguelgrinberg** [comment]
Can you be more specific? There are many examples in this repository. UI for what example?

**Comment by serenachou** [comment]
Hi there @rupamGH  Swiftype is a fully managed service, and does not have a configurable UI. However, you can migrate off of Swiftype into the Elastic Cloud product line, and that would give you access to a deployment where you would have full control to configure the search experience.
