### ISSUE TITLE
inference search notebook error with model_id vs inference_id after 8.13 upgrade

### ISSUE THREAD

**Issue by miguelgrinberg** [elastic/elasticsearch-labs#220]
Issue from @derickson 

## My environment
* colab
* elasticsearch python library 8.13
* elasticsearch 8.13.0 in ESS
* Notebook: https://github.com/elastic/elasticsearch-labs/blob/main/notebooks/search/07-inference.ipynb

The Semantic search step uses the follwing as it's knn query

```
{
        "field": "plot_embedding",
        "query_vector_builder": {
            "text_embedding": {
                "inference_id": "my_openai_embedding_model",
                "model_text": "Fighting movie",
            }
        },
        "k": 10,
        "num_candidates": 100,
    }
 ```

which does not work in 8.13

changing to "model_id" instead of "inference_id" solves the issue. This notebook was written for 8.12

the note at the end is innacurate
> "NOTE: If you use Elasticsearch 8.12, you must change inference_id in the snippet above to model_id."

**Comment by miguelgrinberg** [comment]
This relates to a recent change by @szabosteve. Assigning to him.

**Comment by szabosteve** [comment]
@miguelgrinberg The issue is that the `query_vector_builder` does not accept `inference_id` only `model_id` yet. I opened [a PR](https://github.com/elastic/elasticsearch-labs/pull/221) to fix the problem. Thank you for opening the issue.
