### ISSUE TITLE
elastic_transport.ConnectionTimeout: Connection timed out

### ISSUE THREAD

**Issue by halaneji** [elastic/elasticsearch-labs#227]
when i run :
 python manage.py search_index --rebuild
 have always this error :
anaconda3/envs/DJ_ElasticSearch/lib/python3.6/site-packages/elastic_transport/_node/_http_urllib3.py", line 202, in perform_request
    raise err from None
elastic_transport.ConnectionTimeout: Connection timed out

How can i solve that?

**Comment by joemcelroy** [comment]
Hi there!

Could you tell me what example you're using to get this error? What is in manage.py file?

Joe

**Comment by halaneji** [comment]
Thank you for you reply!
This is the tutorial: https://testdriven.io/blog/django-drf-elasticsearch/ 
and the github project :  https://github.com/testdrivenio/django-drf-elasticsearch/tree/main
When I run : python manage.py search_index --rebuild
I have always the problem of :  elastic_transport.ConnectionTimeout: Connection timed out

**Comment by joemcelroy** [comment]
Hi there.

These issues are for elasticsearch-labs specific issues on our notebooks and sample apps. Reach out in discuss.elastic.co if you need help on general troubleshooting issues.

Just to also help you out, connection time out does sound like theres an issue with connecting to elasticsearch from the client. Worth checking the connection url first and try it out on one of our simple notebooks to see if you can connect. https://github.com/elastic/elasticsearch-labs/blob/main/notebooks/search/00-quick-start.ipynb

Joe
