### ISSUE TITLE
CI notebook failures possibly due to new Langchain integration

### ISSUE THREAD

**Issue by miguelgrinberg** [elastic/elasticsearch-labs#240]
There are two tests from our CI that are now failing, presumably after they started using the updated langchain integration.

The errors:

```
Running notebooks/document-chunking/with-langchain-splitters.ipynb... Failed
...
BadRequestError: BadRequestError(400, 'x_content_parse_exception', "[1:117] [text_embedding] model_id doesn't support values of type: VALUE_NULL")
```

```
Running notebooks/langchain/langchain-using-own-model.ipynb... Failed
...
AttributeError: 'ElasticsearchStore' object has no attribute 'client'
```

@maxjakob any ideas?

Complete run with these failures: https://github.com/elastic/elasticsearch-labs/actions/runs/9113170450

**Comment by maxjakob** [comment]
Great that we have these tests. I should not have removed the attribute. This PR brings it back:
https://github.com/langchain-ai/langchain-elastic/pull/29

**Comment by maxjakob** [comment]
For the first thing `model_id doesn't support values of type: VALUE_NULL`: the new version of `langchain-elasticsearch` does not have a default value for sparse vector models any more (used to be `.elser_model_2`) because it caused some issues with inconsistent cluster states.

**Comment by maxjakob** [comment]
Actually, checking the code again my previous comment doesn't make sense, I see a default value. I have to check more closely...
