### ISSUE TITLE
Jupyter link in “Geospatial search" is broken

### ISSUE THREAD

**Issue by liu-xiao-guo** [elastic/elasticsearch-labs#255]
The "Jupyter notebook" links in the blog "[Journey through the city: Geospatial search made simple with LLM and Elasticsearch](https://www.elastic.co/search-labs/blog/geospatial-search-llm-elasticsearch)" are all broken. I found that their values are https://colab.research.google.com/github/elastic/elasticsearch-labs/blob/main/geospatial-llm/09-geospatial-search.ipynb. However, the actual location for the notebook is https://github.com/elastic/elasticsearch-labs/blob/main/supporting-blog-content/geospatial-llm/09-geospatial-search.ipynb

<img width="1041" alt="image" src="https://github.com/elastic/elasticsearch-labs/assets/8455957/85750bad-4964-4ee9-b008-d30cb3ab8b2b">

**Comment by joemcelroy** [comment]
this has now been fixed. thanks for the spot!
