### ISSUE TITLE
Get index mapping and Get reference document are inconsistent with noteboook in "OpenAI function calling with Elasticsearch"

### ISSUE THREAD

**Issue by liu-xiao-guo** [elastic/elasticsearch-labs#267]
I read through the blog at https://www.elastic.co/search-labs/blog/function-calling-with-elastic, and I found two functions defined in the notebook and blog are insconsistent:

- def get_index_mapping():
- get_ref_document()

The ones defined in the blogs are not correct:

```
def get_index_mapping():

    url = f"""{ES_ENDPOINT}/{ES_INDEX}/_mappings"""

    headers = {
        "Content-type": "application/json",
        "Authorization": f"""ApiKey {ES_API_KEY}""",
    }

```

```
def get_index_mapping():

    url = f"""{ES_ENDPOINT}/{ES_INDEX}/_mappings"""

    headers = {
        "Content-type": "application/json",
        "Authorization": f"""ApiKey {ES_API_KEY}""",
    }

    resp = requests.request("GET", url, headers=headers)
    resp = json.loads(resp.text)
    mapping = json.dumps(resp, indent=4)

    return mapping

```

The correct ones are shown in the attached pictures,
![image](https://github.com/elastic/elasticsearch-labs/assets/8455957/fbe33746-acc9-4a4a-a60a-0c90237f34c4)
![image](https://github.com/elastic/elasticsearch-labs/assets/8455957/ac89a970-9d76-4b1b-80b7-f4a9fecf6067)

**Comment by ashishtiwari1993** [comment]
Merged. Thanks @liu-xiao-guo for pointing this.
