### ISSUE TITLE
hyper link is not displayed correctly in "Semantic search simplified with semantic_text"

### ISSUE THREAD

**Issue by liu-xiao-guo** [elastic/elasticsearch-labs#279]
I think this is a minor mistake in the markdown for the blog at https://www.elastic.co/search-labs/blog/semantic-search-simplified-semantic-text#choosing-an-inference-model

![image](https://github.com/elastic/elasticsearch-labs/assets/8455957/6eb5bc07-4677-42c1-8720-59dfe59d427e)

**Comment by Samiul-TheSoccerFan** [comment]
@liu-xiao-guo  thank you for pointing out the issue. I have created a PR to fix the markdown text.
