### ISSUE TITLE
[BLOG proposal] 

### ISSUE THREAD

**Issue by priscillaparodi** [elastic/elasticsearch-labs#70]
[Blog content](https://docs.google.com/document/d/1d8NpbaKl0TCEZ1n6arI6caT7laZa53PZ6zX0HP5fap8/edit?usp=sharing)

Reviewed by Aditya Tripathi, Carly Richmond, and Philipp Krenn.

**Comment by xeraa** [comment]
@serenachou I guess that should be a good fit and we can turn it into a PR with MDX?

**Comment by serenachou** [comment]
Hey @priscillaparodi  @xeraa  I'm going to close this - to send you to a different content repo. DM incoming!
