### ISSUE TITLE
Potential Addition: Vector and Hybrid search examples in Go

### ISSUE THREAD

**Issue by carlyrichmond** [elastic/elasticsearch-labs#99]
Is there an interest for adding non-Python examples to the labs? Alongside @Anaethelion we're written Go examples to find Gophers in Elasticsearch.

Currently, it's in Markdown format rather than a Python notebook with markdown elements, so it would be good to understand if the search labs blog requires posts in a notebook or can support markdown.

Aware there's been discussion by @xeraa and @joemcelroy so let us know and we can raise a PR to add this contribution. Otherwise, it can live on the Elastic blog instead.

**Comment by joemcelroy** [comment]
Hey Carly! 

Yes and i think this would go nicely in the search-labs repo, which is the codebase for search-labs website. The articles are written with mdx atm and should support code highlighting for go.
